module.exports = {
  GAME_ALREADY_EXISTS: 'GAME_ALREADY_EXISTS',
  GAME_DOES_NOT_EXIST: 'GAME_DOES_NOT_EXIST',
  PLAYER_ALREADY_JOINED: 'PLAYER_ALREADY_JOINED',
  GAME_FULL: 'GAME_FULL',
  START_GAME_MASTER: 'START_GAME_MASTER',
  START_MISSING_PLAYERS: 'START_MISSING_PLAYERS',
};
